# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [35]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [36]:
### [your code here]
print(np.__version__)
np.show_config()

2.2.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/envs/ironhack/include
    lib directory: /opt/anaconda3/envs/ironhack/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/envs/ironhack/lib/pkgconfig
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/envs/ironhack/include
    lib directory: /opt/anaconda3/envs/ironhack/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/envs/ironhack/lib/pkgconfig
    version: 0.3.30
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem,
 

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [37]:
### [your code here]
a = np.random.random((2,3,5))


### 4. Print a.


In [38]:
### [your code here]
print(a)

[[[0.9084134  0.57050697 0.45914024 0.63865607 0.23988194]
  [0.49370749 0.92113078 0.1263315  0.33054861 0.92720423]
  [0.95685221 0.29481803 0.84507404 0.97488227 0.72776455]]

 [[0.01064426 0.05845754 0.85886223 0.60228978 0.61766384]
  [0.77052997 0.11260692 0.30184194 0.34515081 0.78091656]
  [0.98927529 0.2739938  0.5687044  0.40872918 0.61975361]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [39]:
### [your code here]
b = np.ones((5,2,3))



### 6. Print b.


In [40]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [41]:
### [your code here]
print(f'the dimension of a is {a.ndim}') 
print(f'the dimension of b is {b.ndim}') 

a.ndim == b.ndim


the dimension of a is 3
the dimension of b is 3


True


### 8. Are you able to add a and b? Why or why not?


In [42]:
try:
    ab = a + b
except ValueError:
    print("No, a and b cannot be added because their shapes are not compatible.")

No, a and b cannot be added because their shapes are not compatible.




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [43]:
### [your code here]
c = np.transpose(b,(1,2,0))


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [44]:
### [your code here]
d = a + c
print(d)
d.shape


[[[1.9084134  1.57050697 1.45914024 1.63865607 1.23988194]
  [1.49370749 1.92113078 1.1263315  1.33054861 1.92720423]
  [1.95685221 1.29481803 1.84507404 1.97488227 1.72776455]]

 [[1.01064426 1.05845754 1.85886223 1.60228978 1.61766384]
  [1.77052997 1.11260692 1.30184194 1.34515081 1.78091656]
  [1.98927529 1.2739938  1.5687044  1.40872918 1.61975361]]]


(2, 3, 5)


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [45]:
### [your code here]
print(a)
print('------------------------------------------------------------------')
print(d)

print("Each value in d is equal to the corresponding value in a plus 1, because c is an array of ones with the same shape as a, so the addition is performed element-wise.")


[[[0.9084134  0.57050697 0.45914024 0.63865607 0.23988194]
  [0.49370749 0.92113078 0.1263315  0.33054861 0.92720423]
  [0.95685221 0.29481803 0.84507404 0.97488227 0.72776455]]

 [[0.01064426 0.05845754 0.85886223 0.60228978 0.61766384]
  [0.77052997 0.11260692 0.30184194 0.34515081 0.78091656]
  [0.98927529 0.2739938  0.5687044  0.40872918 0.61975361]]]
------------------------------------------------------------------
[[[1.9084134  1.57050697 1.45914024 1.63865607 1.23988194]
  [1.49370749 1.92113078 1.1263315  1.33054861 1.92720423]
  [1.95685221 1.29481803 1.84507404 1.97488227 1.72776455]]

 [[1.01064426 1.05845754 1.85886223 1.60228978 1.61766384]
  [1.77052997 1.11260692 1.30184194 1.34515081 1.78091656]
  [1.98927529 1.2739938  1.5687044  1.40872918 1.61975361]]]
Each value in d is equal to the corresponding value in a plus 1, because c is an array of ones with the same shape as a, so the addition is performed element-wise.



### 12. Multiply a and c. Assign the result to e.


In [46]:
### [your code here]

e = a*c
print(e)
print(c)


[[[0.9084134  0.57050697 0.45914024 0.63865607 0.23988194]
  [0.49370749 0.92113078 0.1263315  0.33054861 0.92720423]
  [0.95685221 0.29481803 0.84507404 0.97488227 0.72776455]]

 [[0.01064426 0.05845754 0.85886223 0.60228978 0.61766384]
  [0.77052997 0.11260692 0.30184194 0.34515081 0.78091656]
  [0.98927529 0.2739938  0.5687044  0.40872918 0.61975361]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]




### 13. Does e equal to a? Why or why not?


In [47]:
### [your code here]

e == a
print(f'a = e because c is a array of ones')

a = e because c is a array of ones




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [48]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(type(d_min))
print(type(d_mean))
print(type(d_max))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [49]:
### [your code here]
f = np.empty(d.shape)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [50]:
### [your code here]
# Fill in 
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            
            value = d[i][j][k]
            
            if value == d_min:
                f[i][j][k] = 0
            elif value == d_mean:
                f[i][j][k] = 50
            elif value == d_max:
                f[i][j][k] = 100
            elif d_min < value < d_mean:
                f[i][j][k] = 25
            elif d_mean < value < d_max:
                f[i][j][k] = 75

print(f)




[[[ 75.  75.  25.  75.  25.]
  [ 25.  75.  25.  25.  75.]
  [ 75.  25.  75.  75.  75.]]

 [[  0.  25.  75.  75.  75.]
  [ 75.  25.  25.  25.  75.]
  [100.  25.  75.  25.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [51]:
### [your code here]
print(d)
print("------------------------------------------------------")
print(f)

[[[1.9084134  1.57050697 1.45914024 1.63865607 1.23988194]
  [1.49370749 1.92113078 1.1263315  1.33054861 1.92720423]
  [1.95685221 1.29481803 1.84507404 1.97488227 1.72776455]]

 [[1.01064426 1.05845754 1.85886223 1.60228978 1.61766384]
  [1.77052997 1.11260692 1.30184194 1.34515081 1.78091656]
  [1.98927529 1.2739938  1.5687044  1.40872918 1.61975361]]]
------------------------------------------------------
[[[ 75.  75.  25.  75.  25.]
  [ 25.  75.  25.  25.  75.]
  [ 75.  25.  75.  75.  75.]]

 [[  0.  25.  75.  75.  75.]
  [ 75.  25.  25.  25.  75.]
  [100.  25.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [52]:
import numpy as np

# Step 1: create empty array (IMPORTANT: dtype=object for strings)
f = np.empty(d.shape, dtype=object)

# Step 2: fill manually
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            
            value = d[i][j][k]
            
            if value == d_min:
                f[i][j][k] = "A"
            elif value == d_mean:
                f[i][j][k] = "C"
            elif value == d_max:
                f[i][j][k] = "E"
            elif d_min < value < d_mean:
                f[i][j][k] = "B"
            elif d_mean < value < d_max:
                f[i][j][k] = "D"

# Step 3: print result
print(f)

[[['D' 'D' 'B' 'D' 'B']
  ['B' 'D' 'B' 'B' 'D']
  ['D' 'B' 'D' 'D' 'D']]

 [['A' 'B' 'D' 'D' 'D']
  ['D' 'B' 'B' 'B' 'D']
  ['E' 'B' 'D' 'B' 'D']]]
